# Maps Bandit check IDs and Semgrep rule patterns to official CWE identifiers

BANDIT_CWE_MAP = {
    "B608": "CWE-89",
    "B601": "CWE-78",
    "B602": "CWE-78",
    "B603": "CWE-78",
    "B604": "CWE-78",
    "B605": "CWE-78",
    "B606": "CWE-78",
    "B607": "CWE-78",
    "B303": "CWE-327",
    "B304": "CWE-327",
    "B305": "CWE-327",
    "B306": "CWE-377",
    "B324": "CWE-327",
    "B105": "CWE-798",
    "B106": "CWE-798",
    "B107": "CWE-798",
    "B108": "CWE-377",
    "B301": "CWE-502",
    "B302": "CWE-502",
    "B403": "CWE-502",
    "B404": "CWE-78",
    "B313": "CWE-611",
    "B314": "CWE-611",
    "B315": "CWE-611",
    "B316": "CWE-611",
    "B317": "CWE-611",
    "B318": "CWE-611",
    "B319": "CWE-611",
    "B101": "CWE-617",
    "B311": "CWE-338",
    "B501": "CWE-295",
    "B502": "CWE-295",
    "B503": "CWE-295",
    "B504": "CWE-295",
    "B505": "CWE-326",
    "B506": "CWE-20",
    "B507": "CWE-295",
    "B201": "CWE-94",
    "B703": "CWE-79",
    "B702": "CWE-79",
    "B110": "CWE-390",
    "B112": "CWE-390",
    "B113": "CWE-400",
    "B320": "CWE-611",
    "B321": "CWE-319",
    "B322": "CWE-134",
    "B323": "CWE-295",
    "B325": "CWE-326",
    "B401": "CWE-319",
    "B402": "CWE-22",
    "B405": "CWE-327",
    "B406": "CWE-20",
    "B407": "CWE-20",
    "B408": "CWE-611",
    "B409": "CWE-611",
    "B410": "CWE-611",
    "B411": "CWE-20",
    "B412": "CWE-20",
    "B413": "CWE-327",
    "B610": "CWE-89",
    "B611": "CWE-89",
    "B612": "CWE-134",
    "B701": "CWE-94",
    "B704": "CWE-94",
    "B104": "CWE-668",
    "B307": "CWE-95",
}

SEMGREP_CWE_MAP = {
    # SQL
    "sql-injection":                        "CWE-89",
    "sqli":                                 "CWE-89",
    "formatted-sql-query":                  "CWE-89",
    "sqlalchemy-execute-raw-query":         "CWE-89",
    "raw-query":                            "CWE-89",
    "execute-raw":                          "CWE-89",
    "tainted-sql-string":                   "CWE-89",
    # XSS
    "xss":                                  "CWE-79",
    "cross-site-scripting":                 "CWE-79",
    "unsafe-innerhtml":                     "CWE-79",
    "dangerouslysetinnerhtml":              "CWE-79",
    "reflected-xss":                        "CWE-79",
    "raw-html-format":                      "CWE-79",
    # Command injection
    "command-injection":                    "CWE-78",
    "os-command-injection":                 "CWE-78",
    "subprocess-shell-true":                "CWE-78",
    "shell-true":                           "CWE-78",
    "subprocess-popen-with-shell":          "CWE-78",
    "subprocess-injection":                 "CWE-78",
    "dangerous-subprocess-use":             "CWE-78",
    # Path traversal
    "path-traversal":                       "CWE-22",
    # Deserialization
    "insecure-deserialization":             "CWE-502",
    "deserialization":                      "CWE-502",
    "avoid-pickle":                         "CWE-502",
    "pickle":                               "CWE-502",
    "marshal-usage":                        "CWE-502",
    "marshal":                              "CWE-502",
    "yaml-load":                            "CWE-502",
    # Crypto / hashing
    "weak-crypto":                          "CWE-327",
    "weak-hash":                            "CWE-327",
    "insecure-hash":                        "CWE-327",
    "md5-used-as-password":                 "CWE-327",
    "insecure-hash-algorithm":              "CWE-327",
    "sha1":                                 "CWE-327",
    "md5":                                  "CWE-327",
    "des":                                  "CWE-327",
    "rc4":                                  "CWE-327",
    "blowfish":                             "CWE-327",
    # Random
    "insecure-random":                      "CWE-338",
    "random":                               "CWE-338",
    "pseudorandom":                         "CWE-338",
    # Secrets / credentials
    "hardcoded-secret":                     "CWE-798",
    "hardcoded-password":                   "CWE-798",
    "hardcoded-credentials":                "CWE-798",
    "hardcoded-token":                      "CWE-798",
    "jwt-hardcoded":                        "CWE-798",
    "generic-api-key":                      "CWE-798",
    "detected-jwt-token":                   "CWE-798",
    # Format string
    "unsafe-formatstring":                  "CWE-134",
    "format-string":                        "CWE-134",
    # Eval / code injection
    "unsafe-eval":                          "CWE-95",
    "eval":                                 "CWE-95",
    "dangerous-template-string":            "CWE-94",
    "render-template-string":               "CWE-94",
    "template-injection":                   "CWE-94",
    "ssti":                                 "CWE-94",
    # Web / HTML
    "missing-integrity":                    "CWE-829",
    "subresource-integrity":                "CWE-829",
    "cors-misconfiguration":                "CWE-346",
    "insecure-cookie":                      "CWE-614",
    "secure-set-cookie":                    "CWE-614",
    "django-secure-set-cookie":             "CWE-614",
    "no-csrf-protection":                   "CWE-352",
    "no-csrf-exempt":                       "CWE-352",
    "django-no-csrf-token":                 "CWE-352",
    "open-redirect":                        "CWE-601",
    "url-redirection":                      "CWE-601",
    "ssrf":                                 "CWE-918",
    "xxe":                                  "CWE-611",
    "xml-external":                         "CWE-611",
    # Docker / container security
    "no-new-privileges":                    "CWE-269",
    "missing-user":                         "CWE-284",
    "missing-user-entrypoint":              "CWE-284",
    "writable-filesystem":                  "CWE-732",
    "writable-filesystem-service":          "CWE-732",
    "add-instead-of-copy":                  "CWE-269",
    "avoid-app-run-with-bad-host":          "CWE-668",
    "expose-port-22":                       "CWE-200",
    "root-in-dockerfile":                   "CWE-269",
    "privileged":                           "CWE-269",
    "docker-expose-ssh":                    "CWE-200",
    # Other
    "prototype-pollution":                  "CWE-1321",
    "detect-non-literal-regexp":            "CWE-730",
    "regex-injection":                      "CWE-730",
    "sensitive-data-exposure":              "CWE-200",
    "information-disclosure":               "CWE-200",
    "missing-ssl-certificate":              "CWE-295",
    "nosql-injection":                      "CWE-943",
    "ldap-injection":                       "CWE-90",
    "xpath-injection":                      "CWE-643",
    "insecure-direct-object":               "CWE-639",
    "mass-assignment":                      "CWE-915",
    "unvalidated-redirect":                 "CWE-601",
    "timing-attack":                        "CWE-208",
    "http-response-splitting":              "CWE-113",
    "log-injection":                        "CWE-117",
    "integer-overflow":                     "CWE-190",
    "null-dereference":                     "CWE-476",
    "use-after-free":                       "CWE-416",
    "buffer-overflow":                      "CWE-120",
    "race-condition":                       "CWE-362",
    "improper-authentication":              "CWE-287",
    "broken-authentication":                "CWE-287",
    "session-fixation":                     "CWE-384",
    "clickjacking":                         "CWE-1021",
    "open-ports":                           "CWE-200",
    "debug-enabled":                        "CWE-489",
    "insecure-tls":                         "CWE-326",
    "weak-tls":                             "CWE-326",
    "certificate-validation":               "CWE-295",
    "request-data-write":                   "CWE-20",
    "sql":                                  "CWE-89",
}

CWE_TITLES = {
    "CWE-20":   "Improper Input Validation",
    "CWE-22":   "Path Traversal",
    "CWE-78":   "OS Command Injection",
    "CWE-79":   "Cross-Site Scripting (XSS)",
    "CWE-89":   "SQL Injection",
    "CWE-90":   "LDAP Injection",
    "CWE-94":   "Code Injection",
    "CWE-95":   "Eval Injection",
    "CWE-113":  "HTTP Response Splitting",
    "CWE-117":  "Log Injection",
    "CWE-120":  "Buffer Overflow",
    "CWE-134":  "Uncontrolled Format String",
    "CWE-190":  "Integer Overflow",
    "CWE-200":  "Sensitive Data Exposure",
    "CWE-208":  "Timing Attack",
    "CWE-269":  "Improper Privilege Management",
    "CWE-284":  "Improper Access Control",
    "CWE-287":  "Improper Authentication",
    "CWE-295":  "Improper Certificate Validation",
    "CWE-319":  "Cleartext Transmission",
    "CWE-326":  "Inadequate Encryption Strength",
    "CWE-327":  "Weak Cryptographic Algorithm",
    "CWE-338":  "Weak Pseudo-Random Number Generator",
    "CWE-346":  "CORS Misconfiguration",
    "CWE-352":  "Cross-Site Request Forgery (CSRF)",
    "CWE-362":  "Race Condition",
    "CWE-377":  "Insecure Temporary File",
    "CWE-384":  "Session Fixation",
    "CWE-390":  "Detection of Error Condition Without Action",
    "CWE-400":  "Uncontrolled Resource Consumption",
    "CWE-416":  "Use After Free",
    "CWE-476":  "NULL Pointer Dereference",
    "CWE-489":  "Active Debug Code",
    "CWE-502":  "Unsafe Deserialization",
    "CWE-601":  "Open Redirect",
    "CWE-611":  "XML External Entity (XXE)",
    "CWE-614":  "Insecure Cookie",
    "CWE-617":  "Reachable Assertion",
    "CWE-639":  "Insecure Direct Object Reference",
    "CWE-643":  "XPath Injection",
    "CWE-668":  "Exposure of Resource to Wrong Sphere",
    "CWE-730":  "Regex Denial of Service",
    "CWE-732":  "Incorrect Permission Assignment",
    "CWE-798":  "Hardcoded Credentials",
    "CWE-829":  "Missing Subresource Integrity",
    "CWE-915":  "Mass Assignment",
    "CWE-918":  "Server-Side Request Forgery (SSRF)",
    "CWE-943":  "NoSQL Injection",
    "CWE-1021": "Clickjacking",
    "CWE-1321": "Prototype Pollution",
}

SEMGREP_SEVERITY_MAP = {
    "ERROR":   "HIGH",
    "WARNING": "MEDIUM",
    "INFO":    "LOW",
}


def get_cwe_from_bandit(check_id: str) -> str:
    return BANDIT_CWE_MAP.get(check_id, "CWE-000")


def get_cwe_from_semgrep(rule_id: str) -> str:
    rule_lower = rule_id.lower()
    for key, cwe in SEMGREP_CWE_MAP.items():
        if key in rule_lower:
            return cwe
    return "CWE-000"


def get_cwe_title(cwe_id: str) -> str:
    return CWE_TITLES.get(cwe_id, "Security Vulnerability")


def get_severity_from_semgrep(raw_severity: str) -> str:
    return SEMGREP_SEVERITY_MAP.get(raw_severity.upper(), "MEDIUM")